### ISSUE TITLE
Since 2023-05-22 matrices are not reporting to argus

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#256]
Failure look like this:
```
14:17:31  + docker run -w /jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/scylla-pkg/scripts/argus-client -e JOB_NAME -e BUILD_URL -e ARGUS_AUTH_TOKEN -v /jenkins:/jenkins -v /home/jenkins:/home/jenkins scylladb/argus-client:latest /app/entry.py --results-dir /jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/xunit --env-file /jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/00-Build.txt --test-type python
14:17:31  INFO:__main__:TestId: 0d66f32d-117b-4b22-8e20-e421c2bc0fef
14:17:31  INFO:__main__:EnvFile: /jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/00-Build.txt
14:17:31  INFO:__main__:Results Directory: /jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/xunit
14:17:31  INFO:__main__:Uploading driver matrix results...
14:17:31  Traceback (most recent call last):
14:17:31    File "/app/entry.py", line 52, in <module>
14:17:31      main()
14:17:31    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
14:17:31      return self.main(*args, **kwargs)
14:17:31    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
14:17:31      rv = self.invoke(ctx)
14:17:31    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
14:17:31      return ctx.invoke(self.callback, **ctx.params)
14:17:31    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
14:17:31      return __callback(*args, **kwargs)
14:17:31    File "/app/entry.py", line 42, in main
14:17:31      client.submit(
14:17:31    File "/usr/local/lib/python3.10/site-packages/argus/client/driver_matrix_tests/client.py", line 187, in submit
14:17:31      self.submit_driver_matrix_run(job_name=build_id, job_url=build_url, test_environment=env, results=results)
14:17:31    File "/usr/local/lib/python3.10/site-packages/argus/client/driver_matrix_tests/client.py", line 199, in submit_driver_matrix_run
14:17:31      self.check_response(response)
14:17:31    File "/usr/local/lib/python3.10/site-packages/argus/client/base.py", line 63, in check_response
14:17:31      raise ArgusClientError(
14:17:31  argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/testrun/driver-matrix-tests/submit', 'SyntaxException')
```

**Comment by fruch** [comment]
@k0machi @temichus any news on this one ?

**Comment by k0machi** [comment]
@fruch looks like a small issue, fixed in the attached PR.
