### ISSUE TITLE
Cloning and running from a release was failing

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#520]
cloneing and running job https://argus.scylladb.com/tests/scylla-cluster-tests/38d7f1c7-1ede-4551-8154-58b188168aa2
failed with the following errors:

![Image](https://github.com/user-attachments/assets/36b31d98-141a-429a-9b7f-f240d5b36a1b)

was was cloned o.k. but the first job didn't seem to have run

**Comment by k0machi** [comment]
Weird, it seems that frontend didn't send parameters for the job, which lead to a cascade of errors. This shouldn't really be happening as we first receive parameters and only then allow to proceed.

```
ip-10-0-2-112 bash[1009789]: [ERROR] <93.173.89.28 - https://argus.scylladb.com/api/v1/jenkins/clone/build - api.testrun_api.clone_build_jenkins_job> - error_handl>
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]: Traceback (most recent call last):
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 880, in ful>
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:     rv = self.dispatch_request()
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:          ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dis>
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:   File "/home/argus/app/argus/backend/service/user.py", line 261, in wrapped_view
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:     return view(*args, **kwargs)
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:            ^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:   File "/home/argus/app/argus/backend/controller/testrun_api.py", line 433, in clone_build_jenkins_job
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:     result = service.clone_build_job(build_id=payload["buildId"], params=payload["parameters"])
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]:                                                                          ~~~~~~~^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]: KeyError: 'parameters'
Nov 24 09:37:46 ip-10-0-2-112 bash[1009789]: [pid: 1009789|app: 0|req: 24902/1362361] 93.173.89.28 () {68 vars in 2312 bytes} [Sun Nov 24 09:37:46 2024] POST /api/v1/jenkins/clone>
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]: [ERROR] <93.173.89.28 - https://argus.scylladb.com/api/v1/jenkins/queue_info - api.testrun_api.get_queue_info> - error_handlers::handl>
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]: Traceback (most recent call last):
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 880, in ful>
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:     rv = self.dispatch_request()
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:          ^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dis>
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:   File "/home/argus/app/argus/backend/service/user.py", line 261, in wrapped_view
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:     return view(*args, **kwargs)
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:            ^^^^^^^^^^^^^^^^^^^^^
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:   File "/home/argus/app/argus/backend/controller/testrun_api.py", line 359, in get_queue_info
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]:     raise Exception("No queueItem provided")
Nov 24 09:37:46 ip-10-0-2-112 bash[1022444]: Exception: No queueItem provided
```

Maybe a network issue or something to that effect between frontend and backend. I'll take a look at the parameter send part if there's anything that can potentially break there.

**Comment by roydahan** [comment]
If we can't understand what's the root cause and it doesn't reproduce. you can close.

**Comment by fruch** [comment]
we should now have more debugging info to help us figure it next time
